import type { Metadata } from 'next';
import './globals.css';
import ThemeProvider from '@components/ThemeProvider';
import Navigation from '@components/Navigation';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='h-dvh'>
        <ThemeProvider>
          <Navigation />
          <div className='grid justify-items-center items-start pt-20 text-center h-[calc(100vh-5rem)]'>{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
